### ISSUE TITLE
[Epic 4.1] Фильтр «Отрасли и ЗП» presentation и ui

### ISSUE THREAD

**Issue by Evlenium** [HUEY-news/Diploma#138]
- [x] Переход на экран настроек параметров фильтрации осуществляется нажатием на кнопку фильтра в правом верхнем углу главного экрана.
- [x] В поле ввода уровня зарплаты отображается подсказка (hint), если текст не введён.
- [x] В поле ввода уровня зарплаты разрешено вводить только целочисленные значения.
- [x] Если поле ввода уровня зарплаты не пустое, видна кнопка для его очистки. Нажатие на эту кнопку удаляет введённый текст.
- [x] При нажатии на пункт «Отрасль» пользователь переходит на экран выбора отрасли компании.
- [x] Вёрстка экрана «Отрасль».
