### ISSUE TITLE
[Epic 4.1] Фильтр «Отрасли и ЗП» presentation и ui

### ISSUE THREAD

**Issue by Evlenium** [HUEY-news/Diploma#143]
- [x] Кнопка «Применить» появляется, если пользователь указал фильтр, отличающийся от предыдущего. Нажатие на кнопку «Применить» приводит к сохранению выбранных настроек фильтра и применению фильтра для всех последующих запросов на поиск вакансий до изменения фильтра.
- [x] Кнопка «Сбросить» появляется, если пользователь указал хотя бы одно значение фильтров.
- [x] Если приложению не удалось получить список отраслей, то на экране выбора отрасли пользователь видит соответствующий плейсхолдер. В противном случае пользователь видит список отраслей.
