### ISSUE TITLE
[Epic 4.2] Фильтр «Отрасли и ЗП» presentation и ui

### ISSUE THREAD

**Issue by yulia1Volkova** [HUEY-news/Diploma#152]
- [ ] При нажатии на любой невыбранный элемент списка отраслей этот элемент становится выбранным (отображается в выбранном состоянии), а все остальные — не выбранными.
- [ ] Кнопка «Выбрать» на экране выбора отрасли видна, только если в списке есть выбранный элемент.
- [ ] При нажатии на кнопку «Выбрать» на экране выбора отрасли пользователь возвращается на экран настроек фильтра и видит название выбранной отрасли в области для отображения отрасли.
- [ ] На экране выбора отрасли присутствует поле для поиска отрасли. Если поле ввода пустое, то в нём отображается подсказка (hint).
- [ ] Если поле ввода поискового запроса не пустое, то в списке присутствуют только те отрасли, названия которых содержат введённый в поле текст.
- [ ] Допустима реализация фильтрации списка на уровне адаптера или с использованием ViewModel.
- [ ] Если в приложении нет сохранённых настроек фильтра, то по умолчанию на экране никакие параметры фильтрации не должны быть выбраны. В том числе пустое поле ввода и снята галочка «Не показывать без зарплаты».
- [ ] Если в сохранённых настройках фильтрации в приложении указан уровень зарплаты, то при входе на экран фильтра пользователь должен видеть это значение в поле ввода.
- [ ] Если в сохранённых настройках фильтрации в приложении указан параметр «Не показывать без зарплаты», то при входе на экран фильтра пользователь должен видеть соответствующий чекбокс в выбранном состоянии.
- [ ] При нажатии на кнопку «Сбросить» все указанные настройки должны удалиться.
- [ ] Если в настройках параметров фильтрации есть выбранная отрасль компании, то название отрасли отображается в области для отображения отрасли компании.
- [ ] Если в настройках фильтрации уже есть выбранная отрасль, то соответствующий элемент списка на экране списка отраслей находится в выбранном состоянии.
- [ ] Любые изменения настроек фильтра сохраняются автоматически и не сбрасываются даже после закрытия приложения. При последующих переходах на экран настроек параметров фильтрации пользователь должен видеть актуальные настройки в соответствующих полях.
- [ ] Если в приложении есть сохранённые настройки параметров фильтрации, то все поисковые запросы должны выполняться с учётом всех непустых параметров.
- [ ] Нажатие на кнопку «Применить» на экране фильтра возвращает пользователя на экран поиска. И если поле ввода поискового запроса было не пустым, то этот поисковый запрос должен автоматически выполниться повторно с применением актуальных настроек фильтрации.
- [ ] При нажатии на кнопку «Назад» пользователь возвращается на экран поиска, и актуальные настройки фильтра к последнему поисковому запросу не применяются автоматически.
- [ ] Если в приложении есть сохранённые непустые настройки параметров фильтрации, то кнопка фильтра на главном экране находится в подсвеченном состоянии.
