### ISSUE TITLE
[Epic 5.1] Фильтр «Место работы» data и domain

### ISSUE THREAD

**Issue by Evlenium** [HUEY-news/Diploma#158]
- [x] Создан Retrofit API interface с suspend-методом для выполнения запроса на получение areas.

- [x] Для запроса areas в пакете data.dto созданы классы запроса (Request), ответа (Response) и, если он необходим, класс элемента списка areas.

- [x] В компоненте для выполнения сетевых запросов получение areas выполняется не в главном потоке.

- [x] Описан и реализован Repository, предоставляющий метод для получения списка стран.

- [x] Описан и реализован Interactor, обеспечивающий ViewModel связь c Domain-слоем.

- [x] DTO-классы не используются за пределами Data-слоя. В пакете domain.models созданы соответствующие классы для использования в слое представления.

- [x] Присутствует логика определения стран (по пустому значению параметра parentId).
