### ISSUE TITLE
[Epic 5.1] Фильтр «Место работы» presentation и ui

### ISSUE THREAD

**Issue by Evlenium** [HUEY-news/Diploma#160]
- [x] Если приложению не удалось получить список стран, то на экране выбора страны пользователь видит соответствующий плейсхолдер. В противном случае пользователь видит список стран.
- [x] Если приложению не удалось получить список регионов, то на экране выбора региона пользователь видит соответствующий плейсхолдер. В противном случае пользователь видит список регионов.
- [x] На экране выбора страны присутствует поле для поиска страны. Если поле ввода пустое, то в нём отображается подсказка (hint).
- [x] Если поле ввода поискового запроса не пустое, то в списке присутствуют только те страны, названия которых содержат введённый в поле текст.
- [x] Допустима реализация фильтрации списка на уровне адаптера или с использованием ViewModel
