### ISSUE TITLE
[Epic 5.1] Фильтр «Место работы» presentation и ui

### ISSUE THREAD

**Issue by Evlenium** [HUEY-news/Diploma#165]
- [x]  При нажатии на пункт «Место работы» должен открываться экран выбора места работы.
- [x] При нажатии на пункт «Страна» пользователь переходит на экран выбора страны.
- [x] Когда пользователь на экране выбора страны нажимает на элемент списка стран, он возвращается на экран выбора места работы и видит название выбранной страны в области для отображения страны.
