### ISSUE TITLE
[Epic 5.2] Фильтр «Место работы» data и domain

### ISSUE THREAD

**Issue by Evlenium** [HUEY-news/Diploma#169]
- [x] Описан и реализован Repository, предоставляющий метод для получения списка регионов.
- [x] Описан и реализован Interactor, обеспечивающий ViewModel связь c Domain-слоем
- [x] Присутствует логика определения регионов по параметрам parentId и areas.
