### ISSUE TITLE
[Epic 5.2] Фильтр «Место работы» presentation и ui

### ISSUE THREAD

**Issue by Evlenium** [HUEY-news/Diploma#171]
- [x] При нажатии на пункт «Регион» пользователь переходит на экран выбора региона.
- [x] Если приложению не удалось получить список регионов, то на экране выбора региона пользователь видит соответствующий плейсхолдер. В противном случае пользователь видит список регионов.
- [x] На экране выбора региона присутствует поле для поиска региона. Если поле ввода пустое, то в нём отображается подсказка (hint).
- [x] Если поле ввода поискового запроса не пустое, то в списке присутствуют только те регионы, названия которых содержат введённый в поле текст.
- [x] Допустима реализация фильтрации списка на уровне адаптера или с использованием ViewModel.
