### ISSUE TITLE
[Epic 4.1] Остатки.

### ISSUE THREAD

**Issue by HUEY-news** [HUEY-news/Diploma#172]
- [ ] Ограничить возможность выбора только одной отрасли
- [ ] Передача отрасли на экран Фильтров
- [ ] Откорректировать положение подсказки при пустом EditText
