### ISSUE TITLE
[Epic 5.2] Фильтр «Место работы» presentation и ui with shared

### ISSUE THREAD

**Issue by Evlenium** [HUEY-news/Diploma#182]
- [x] Если в настройках фильтрации уже есть выбранные значения для страны, то на экране выбора места работы отображается соответствующая страна. В противном случае область для отображения страны должна быть пустой.
 - [x] Если в настройках фильтрации уже есть выбранный регион, то на экране выбора места работы отображается соответствующий регион. В противном случае область для отображения региона должна быть пустой.
 - [x] Если в настройках фильтрации уже есть выбранная страна, то при переходе на экран выбора региона пользователь видит список только тех регионов, которые относятся к выбранной стране. В противном случае пользователь видит список всех доступных регионов, которые не являются странами.
 - [x] Когда пользователь на экране выбора региона нажимает на элемент списка регионов, он возвращается на экран выбора места работы и видит название выбранного региона в области для отображения региона.
 - [x] Если в момент нажатия на элемент списка регионов на экране выбора региона в настройках фильтрации не было выбранной страны, то автоматически выбирается страна, к которой относится этот регион. Название этой страны должно отображаться на экране выбора места работы.
 - [x] Если в настройках фильтрации есть выбранная страна, то пользователь видит кнопку «Выбрать» на экране выбора места работы. Нажатие на эту кнопку возвращает пользователя на экран настроек параметров фильтрации поисковых запросов.
 - [x] Если в настройках фильтрации есть выбранный регион, то пользователь видит кнопку «Выбрать» на экране выбора места работы. Нажатие на эту кнопку возвращает пользователя на экран настроек параметров фильтрации поисковых запросов.
 - [x] Выбранные страна отображается на экране настроек параметров фильтрации поисковых запросов.
 - [x] Выбранный регион отображаются на экране настроек параметров фильтрации поисковых запросов. Если выбрана только страна, то отображается только страна. Если выбран регион, то отображается страна и регион.
 - [x] Сохранённые настройки места работы применяются к поисковым запросам аналогично остальным настройкам параметров фильтрации.
