### ISSUE TITLE
[Epic 4] Чек-лист

### ISSUE THREAD

**Issue by HUEY-news** [HUEY-news/Diploma#192]
### **Задача 1**
**В рамках данной задачи необходимо реализовать:**
- [x] Переход на экран «Фильтр» и его вёрстку (в том числе, поведение поля ввода уровня ЗП и видимости кнопок).
- [x] Выполнение и обработка запроса списка отраслей с полной проработкой слоёв Data/Domain/Presentation.
- [x] Отображение списка отраслей на экране «Отрасли».

**Presentation и UI**
- [x] Переход на экран настроек параметров фильтрации осуществляется нажатием на кнопку фильтра в правом верхнем углу главного экрана.
- [x] В поле ввода уровня зарплаты отображается подсказка (hint), если текст не введён.
- [x] В поле ввода уровня зарплаты разрешено вводить только целочисленные значения.
- [x] Если поле ввода уровня зарплаты не пустое, видна кнопка для его очистки. Нажатие на эту кнопку удаляет введённый текст.
- [x] Кнопка «Применить» появляется, если пользователь указал фильтр, отличающийся от предыдущего. Нажатие на кнопку «Применить» приводит к сохранению выбранных настроек фильтра и применению фильтра для всех последующих запросов на поиск вакансий до изменения фильтра.
- [x] Кнопка «Сбросить» появляется, если пользователь указал хотя бы одно значение фильтров.
- [x] При нажатии на пункт «Отрасль» пользователь переходит на экран выбора отрасли компании.
- [x] Если приложению не удалось получить список отраслей, то на экране выбора отрасли пользователь видит соответствующий плейсхолдер. В противном случае пользователь видит список отраслей.

**Data и Domain**
- [x] Создан Retrofit API interface с suspend-методом для выполнения запроса на получение отраслей.
- [x] Для запроса отраслей в пакете data.dto созданы классы запроса (Request), ответа (Response) и, если нужно, класс элемента списка отраслей.
- [x] В компоненте для выполнения сетевых запросов получение отраслей выполняется не в главном потоке.
- [x] Описан и реализован Repository, предоставляющий метод для получения списка отраслей.
- [x] Описан и реализован Interactor, обеспечивающий ViewModel связь с Domain-слоем.
- [x] DTO-классы не используются за пределами Data-слоя. В пакете domain.models созданы соответствующие классы для использования в слое представления.

### **Задача 2**
**В рамках данной задачи необходимо реализовать:**
- [x] UI и логику поиска по списку отраслей.
- [x] Поведение кнопки «Выбрать» и выбор отрасли с отображением на экране настроек фильтра.
- [x] Логику сохранения и применения настроек фильтра («Уровень ЗП», «Не показывать без ЗП», «Отрасль»).

**Presentation и UI**
- [x] При нажатии на любой невыбранный элемент списка отраслей этот элемент становится выбранным (отображается в выбранном состоянии), а все остальные — не выбранными.
- [x] Кнопка «Выбрать» на экране выбора отрасли видна, только если в списке есть выбранный элемент.
- [x] При нажатии на кнопку «Выбрать» на экране выбора отрасли пользователь возвращается на экран настроек фильтра и видит название выбранной отрасли в области для отображения отрасли.
- [x] На экране выбора отрасли присутствует поле для поиска отрасли. Если поле ввода пустое, то в нём отображается подсказка (hint).
- [x] Если поле ввода поискового запроса не пустое, то в списке присутствуют только те отрасли, названия которых содержат введённый в поле текст.
- [x] Допустима реализация фильтрации списка на уровне адаптера или с использованием ViewModel.
- [x] Если в приложении нет сохранённых настроек фильтра, то по умолчанию на экране никакие параметры фильтрации не должны быть выбраны. В том числе пустое поле ввода и снята галочка «Не показывать без зарплаты».
- [x] Если в сохранённых настройках фильтрации в приложении указан уровень зарплаты, то при входе на экран фильтра пользователь должен видеть это значение в поле ввода.
- [x] Если в сохранённых настройках фильтрации в приложении указан параметр «Не показывать без зарплаты», то при входе на экран фильтра пользователь должен видеть соответствующий чекбокс в выбранном состоянии.
- [x] При нажатии на кнопку «Сбросить» все указанные настройки должны удалиться.
- [x] Если в настройках параметров фильтрации есть выбранная отрасль компании, то название отрасли отображается в области для отображения отрасли компании.
- [x] Если в настройках фильтрации уже есть выбранная отрасль, то соответствующий элемент списка на экране списка отраслей находится в выбранном состоянии.
- [x] Любые изменения настроек фильтра сохраняются автоматически и не сбрасываются даже после закрытия приложения. При последующих переходах на экран настроек параметров фильтрации пользователь должен видеть актуальные настройки в соответствующих полях.
- [x] Если в приложении есть сохранённые настройки параметров фильтрации, то все поисковые запросы должны выполняться с учётом всех непустых параметров.
- [x] Нажатие на кнопку «Применить» на экране фильтра возвращает пользователя на экран поиска. И если поле ввода поискового запроса было не пустым, то этот поисковый запрос должен автоматически выполниться повторно с применением актуальных настроек фильтрации.
- [x] При нажатии на кнопку «Назад» пользователь возвращается на экран поиска, и актуальные настройки фильтра к последнему поисковому запросу не применяются автоматически.
- [x] Если в приложении есть сохранённые непустые настройки параметров фильтрации, то кнопка фильтра на главном экране находится в подсвеченном состоянии.

**Data и Domain**
- [x] В Data-слое реализован класс, выполняющий чтение и запись настроек параметров фильтрации поискового запроса в SharedPreferences.
- [x] Описан и реализован интерфейс Repository, предоставляющий методы для записи и чтения настроек фильтрации.
- [x] Для сохранения и доступа к сохранённым настройкам из слоя представления создан и реализован интерфейс Interactor.
- [x] Interactor для работы с настройками фильтра внедрён как зависимость во ViewModel экрана настроек параметров фильтрации.
- [x] Для доступа к сохранённым настройкам фильтра на экране поиска вo ViewModel используется соответствующий Interactor.
- [x] Метод API интерфейса для выполнения поискового запроса модифицирован для передачи параметров фильтрации.
- [x] Код реализации Repository, осуществляющего отправку поисковых запросов, модифицирован для передачи актуальных параметров фильтрации. Допускается передача параметров фильтрации на уровне ViewModel экрана поиска.
