### ISSUE TITLE
[Epic 0] Базовая структура проекта

### ISSUE THREAD

**Issue by HUEY-news** [HUEY-news/Diploma#49]
**Разработка любого мобильного приложения начинается с базовой настройки проекта. Вам предстоит подготовиться к работе в команде, где каждый из вас должен иметь возможность работать над своими задачами независимо от других разработчиков. Подготовка включает в себя следующие задачи:**

- [x] Настройки build.gradle файлов и AndroidManifest.xml. Все основные настройки проекта лучше произвести заранее: минимально поддерживаемая версия Android, ориентация экрана приложения, ссылка на класс Application и основную тему, список всех библиотек, от которых зависит приложение (Retrofit, Room, Glide и т.д.). Внимательно изучите проект и обсудите в команде все необходимые настройки.
- [x] Иконка приложения. Если есть необходимые материалы для создания иконки приложения, то её лучше подготовить заранее.
- [x] Структура пакетов. В заготовке проекта, который вы форкнули, уже предложена структура пакетов для чистой архитектуры, но вы не обязаны следовать именно ей. Обсудите в команде вместе с наставником, какую структуру пакетов будете использовать.
- [x] Общие компоненты Data-слоя. В проекте будут присутствовать компоненты, которые необходимы для работы сразу над несколькими задачами. Например, экраны «Поиск вакансий» и «Детали вакансии» нужны для реализации готового компонента Network Client, отвечающего за выполнение сетевых запросов: наиболее эффективно создавать его отдельно и заранее. Выделите подобные компоненты вместе с командой и реализуйте в рамках данного эпика. Также в рамках базовой конфигурации проекта можно обсудить и описать основные сущности базы данных и реализовать её инициализацию.
- [x] Вспомогательные классы и функции. Помимо полноценных компонентов Data-слоя, вам в процессе могут понадобиться различные вспомогательные функции (например, debounce) и классы (например, для определения доступности подключения к интернету). Удобнее всего их добавить в процессе базовой настройки проекта.
- [x] Dependency Injection. Обсудите в команде, какие модули для внедрения зависимостей вам понадобятся и по возможности опишите инициализацию для общих компонентов.
- [x] Темы и стили. Аналогично общим компонентам Data-слоя, каждому разработчику в команде потребуются заранее подготовленные параметры темы и некоторые стили. С цветовой палитрой всего проекта вы можете заранее подготовить светлую и тёмную темы приложения и указать её в манифесте проекта.
- [x] Граф навигации и заглушки экранов. Когда известно, из каких экранов будет состоять приложение, эффективнее всего описать граф навигации полностью и заранее. В качестве наполнения экранов, над которыми будет вестись работа, можно использовать «заглушки», представляющие собой layout-файлы без UI-элементов, с одним TextView, отображающим название экрана, и, возможно, кнопки для перехода на другие экраны (например, с экрана «Поиск вакансий» на экран «Фильтр»).
- [x] BottomNavigationView. Настраивать основной компонент навигации тоже нужно заранее, чтобы несколько разработчиков могли одновременно вести работу и сдавать задачи, связанные с разными экранами приложения.
- [x] Экран «Команда». Данный экран не содержит сложной логики и его можно реализовать сразу же, без создания промежуточных заглушек.

**Помимо общих требований к приложению, задачи данного эпика должны соответствовать следующим критериям:**

- [x] Проект компилируется и запускается без сбоев и ошибок.
- [x] Нижняя панель навигации видна при запуске приложения. Внешний вид панели навигации соответствует дизайну как в светлой, так и в тёмной теме. Нажатие на табы панели переключает экраны («заглушки») в контейнере.
- [x] Переход на экран «Команда» осуществляется нажатием на соответствующую вкладку нижней панели навигации.
- [x] Экран «Команда» можно реализовать без использования ViewModel.
